Added j2cl module & considered webfx APi changes

diff --git a/.github/workflows/builds.yml b/.github/workflows/builds.yml
--- a/.github/workflows/builds.yml
+++ b/.github/workflows/builds.yml
@@ -26,19 +26,20 @@ name: Multi-OS builds
 on:
   push:
     branches: [ main ]
+  workflow_dispatch:
 
 jobs:
   build:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        app: [{name: 'WebFXWebsite', module-token: 'webfx-website', gwt-token: 'webfx_website', web-push-branch: 'main', ios-bundle-id: 'dev.webfx.website', version: '0.1.0-SNAPSHOT'}]
+        app: [{name: 'WebFXWebsite', module-token: 'webfx-website', gwt-token: 'webfx_website', gwt-push-branch: 'gwt', j2cl-push-branch: 'main', ios-bundle-id: 'dev.webfx.website', version: '0.1.0-SNAPSHOT'}]
         os-config:  [1]
         include:
           - os-config: 1 # Generates builds 1) 2) 3) 4) & 5)
             os: ubuntu-latest
             # Note: 1) must run on Ubuntu because the GitHub push action (to update the web-build branch) works only on Ubuntu
-            web-artifact-suffix:           'Web.war'                            # build 1)
+            gwt-artifact-suffix:           'Web.war'                            # build 1)
             #fatjar-artifact-suffix:        'Linux-x64-runnable.jar'             # build 2)
             #jvm-deb-artifact-suffix:       'Linux-x64-jvm-package.deb'          # build 3)
             #jvm-rpm-artifact-suffix:       'Linux-x64-jvm-package.rpm'          # build 4)
@@ -52,6 +53,8 @@ jobs:
       app-openjfx-module-dir:    ./${{ matrix.app.module-token }}-application-openjfx
       app-gwt-module-dir:        ./${{ matrix.app.module-token }}-application-gwt
       app-gwt-build-dir:         ./${{ matrix.app.module-token }}-application-gwt/target/${{ matrix.app.module-token }}-application-gwt-${{ matrix.app.version }}/${{ matrix.app.gwt-token }}_application_gwt
+      app-j2cl-module-dir:       ./${{ matrix.app.module-token }}-application-j2cl
+      app-j2cl-build-dir:        ./${{ matrix.app.module-token }}-application-j2cl/target/${{ matrix.app.module-token }}-application-j2cl-${{ matrix.app.version }}/${{ matrix.app.module-token }}-application-j2cl
       app-gluon-module-dir:      ./${{ matrix.app.module-token }}-application-gluon
       web-push-repository-name:  'webfx-netlify'
       web-push-repository-owner: 'webfx-project'
@@ -61,8 +64,18 @@ jobs:
       xcode-version: '14.2.0'
       API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
       GLUON_LICENSE: ${{ secrets.GLUON_LICENSE }}
-      GLUON_IOS_CERTIFICATES_FILE_BASE64: ${{ secrets.GLUON_IOS_CERTIFICATES_FILE_BASE64 }}
+      GLUON_ANDROID_VERSION_CODE: ${{ vars.GLUON_ANDROID_VERSION_CODE }}
+      GLUON_ANDROID_VERSION_NAME: ${{ vars.GLUON_ANDROID_VERSION_NAME }}
+      GLUON_ANDROID_KEYSTORE_BASE64: ${{ secrets.GLUON_ANDROID_KEYSTORE_BASE64 }}
+      GLUON_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.GLUON_ANDROID_KEYSTORE_PASSWORD }}
+      GLUON_ANDROID_KEYALIAS: ${{ secrets.GLUON_ANDROID_KEYALIAS }}
+      GLUON_ANDROID_KEYALIAS_PASSWORD: ${{ secrets.GLUON_ANDROID_KEYALIAS_PASSWORD }}
+      GLUON_ANDROID_SERVICE_ACCOUNT_JSON: ${{ secrets.GLUON_ANDROID_SERVICE_ACCOUNT_JSON }}
+      GLUON_IOS_CERTIFICATES_BASE64: ${{ secrets.GLUON_IOS_CERTIFICATES_BASE64 }}
+      GLUON_IOS_CERTIFICATES_PASSWORD: ${{ secrets.GLUON_IOS_CERTIFICATES_PASSWORD }}
       GLUON_IOS_APPSTORE_KEY_ID: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
+      GLUON_IOS_APPSTORE_PRIVATE_KEY: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
+      GLUON_IOS_APPSTORE_ISSUER_ID: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
 
     steps:
 
@@ -112,20 +125,26 @@ jobs:
       ##################################################################################################################
 
       # Building this repository with JDK 13+ (Java 11 target)
-      - name: Build this repository (no OpenJFX fat jar - no GWT build)
-        run: mvn -B -P '!gwt-compile,!openjfx-fatjar,!openjfx-desktop' install
+      - name: Build this repository
+        run: mvn -B install
         working-directory: ${{ env.app-repo-dir }}
 
-      # Building this repository with JDK 13+ (Java 11 target) including a GWT compilation (if required)
-      - if: matrix.web-artifact-suffix != null
-        name: Build this application (OpenJFX fat jar + GWT build)
-        run: mvn -B -P 'gwt-compile,openjfx-fatjar,openjfx-desktop' package
+      # Building GWT application (if required)
+      - if: matrix.gwt-artifact-suffix != null || matrix.app.gwt-push-branch != null && matrix.os-config == 1
+        name: Build GWT application
+        run: mvn -B -P gwt-compile package
         working-directory: ${{ env.app-parent-module-dir }}
 
-      # Or building this repository with JDK 13+ (Java 11 target) excluding a GWT compilation
-      - if: matrix.web-artifact-suffix == null
-        name: Build this application (OpenJFX fat jar - no GWT build)
-        run: mvn -B -P '!gwt-compile,openjfx-fatjar,openjfx-desktop' package
+      # Building J2CL application (if required)
+      - if: matrix.j2cl-artifact-suffix != null || matrix.app.j2cl-push-branch != null && matrix.os-config == 1
+        name: Build J2CL application
+        run: mvn -B -P j2cl package
+        working-directory: ${{ env.app-parent-module-dir }}
+
+      # Building OpenJFX fat jar and installers (if required)
+      - if: matrix.fatjar-artifact-suffix != null
+        name: Build OpenJFX fat jar and installers
+        run: mvn -B -P 'openjfx-fatjar,openjfx-desktop' package
         working-directory: ${{ env.app-parent-module-dir }}
 
 
@@ -133,19 +152,31 @@ jobs:
       #                        Updating the Web build branch (will update the live demo)                               #
       ##################################################################################################################
 
-      - if: matrix.web-artifact-suffix != null && env.API_GITHUB_TOKEN != ''
-        name: Push GWT build to ${{ matrix.app.web-push-branch }} branch
+      - if: matrix.os-config == 1 && matrix.app.gwt-push-branch != null && env.API_GITHUB_TOKEN != ''
+        name: Push GWT build to ${{ matrix.app.gwt-push-branch }} branch
         uses: cpina/github-action-push-to-another-repository@master
         env:
-          API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
+          API_TOKEN_GITHUB: ${{ env.API_GITHUB_TOKEN }}
         with:
           source-directory: ${{ env.app-gwt-build-dir }}
           destination-repository-username: ${{ env.web-push-repository-owner }}
           destination-repository-name: ${{ env.web-push-repository-name }}
-          target-branch: ${{ matrix.app.web-push-branch }}
+          target-branch: ${{ matrix.app.gwt-push-branch }}
           destination-github-username: ${{ env.web-push-username }}
           user-email: ${{ env.web-push-email }}
 
+      - if: matrix.os-config == 1 && matrix.app.j2cl-push-branch != null && env.API_GITHUB_TOKEN != ''
+        name: Push J2CL build to ${{ matrix.app.j2cl-push-branch }} branch
+        uses: cpina/github-action-push-to-another-repository@master
+        env:
+          API_TOKEN_GITHUB: ${{ env.API_GITHUB_TOKEN }}
+        with:
+          source-directory: ${{ env.app-j2cl-build-dir }}
+          destination-repository-username: ${{ env.web-push-repository-owner }}
+          destination-repository-name: ${{ env.web-push-repository-name }}
+          target-branch: ${{ matrix.app.j2cl-push-branch }}
+          destination-github-username: ${{ env.web-push-username }}
+          user-email: ${{ env.web-push-email }}
 
       ##################################################################################################################
       #                                           Staging artifacts                                                    #
@@ -166,9 +197,9 @@ jobs:
       ##################################################################################################################
 
       # Staging 1)
-      - if: matrix.web-artifact-suffix != null
+      - if: matrix.gwt-artifact-suffix != null
         name: Copy Web archive to staging
-        run: cp ${{ env.app-gwt-module-dir }}/target/*.war staging/${{ env.app-name }}-${{ matrix.web-artifact-suffix }}
+        run: cp ${{ env.app-gwt-module-dir }}/target/*.war staging/${{ env.app-name }}-${{ matrix.gwt-artifact-suffix }}
 
       # Staging 2) | 7) | 11)
       - if: matrix.fatjar-artifact-suffix != null
@@ -252,7 +283,7 @@ jobs:
       - uses: gluonhq/setup-graalvm@master
         # set GITHUB_TOKEN to avoid exceeding GitHub's API rate limit
         env:
-          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ env.API_GITHUB_TOKEN }}
 
       # Gluon needs additional libraries on Linux
       - if: runner.os == 'Linux'
@@ -264,7 +295,7 @@ jobs:
         name: Gluon License
         uses: gluonhq/gluon-build-license@v1
         with:
-          gluon-license: ${{ secrets.GLUON_LICENSE }}
+          gluon-license: ${{ env.GLUON_LICENSE }}
 
       # Invoking the Gluon Client Maven plugin to build the native Desktop app (chaining build & package goals)
       - if: matrix.gluon-desktop-artifact-suffix != null
@@ -286,7 +317,7 @@ jobs:
       # Staging 5) | 14)
       - if: matrix.gluon-desktop-artifact-suffix != null && runner.os != 'Windows'
         name: Copy native Desktop to staging (Linux or MacOS)
-        run: cp ${{ env.app-gluon-module-dir }}/target/gluonfx/${{ matrix.gluon-desktop-arch-token }}/${{ matrix.app.module-token }}* staging/${{ env.app-name }}-${{ matrix.gluon-desktop-artifact-suffix }}
+        run: cp ${{ env.app-gluon-module-dir }}/target/gluonfx/${{ matrix.gluon-desktop-arch-token }}/${{ matrix.app.gluon-token }}* staging/${{ env.app-name }}-${{ matrix.gluon-desktop-artifact-suffix }}
 
       # Staging 10)
       - if: matrix.gluon-desktop-artifact-suffix != null && runner.os == 'Windows'
@@ -300,21 +331,53 @@ jobs:
       #  6) App-Android-aarch64-native-package.apk : Android native app (Gluon)                                        #
       ##################################################################################################################
 
-      # All prerequisite have already be done when building the Desktop qpps
+      # Importing the Android keystore if provided
+      - if: matrix.gluon-android-arch-token != null && env.GLUON_ANDROID_KEYSTORE_BASE64 != '' && env.GLUON_ANDROID_KEYALIAS != ''
+        name: Setup Android Keystore
+        id: android_keystore_file
+        uses: timheuer/base64-to-file@v1.2
+        with:
+          fileName: 'android.keystore'
+          encodedString: ${{ env.GLUON_ANDROID_KEYSTORE_BASE64 }}
+
 
       # Invoking the Gluon Client Maven plugin to build the native Android app (chaining build & package goals)
       - if: matrix.gluon-android-arch-token != null
+        id: android_gluon_build
         name: Gluon Build for Android
-        run: mvn -B -P 'gluon-android' clean gluonfx:build gluonfx:package # May take a while
+        run: |
+          export ANDROID_SDK=$ANDROID_HOME # Otherwise GluonFX 1.0.16 package task is failing
+          mvn -B -P 'gluon-android' clean gluonfx:build gluonfx:package # May take a while
         env:
           GRAALVM_HOME: ${{ env.JAVA_HOME }}
+          GLUON_ANDROID_KEYSTOREPATH: ${{ steps.android_keystore_file.outputs.filePath }}
         working-directory: ${{ env.app-gluon-module-dir }}
+        continue-on-error: true # So that we print the Gluon logs in the next step to help investigating the error
+
+      - if: matrix.gluon-android-arch-token != null
+        name: Print Android Gluon build logs (for debug)
+        run: tail -n+1 ${{ env.app-gluon-module-dir }}/target/gluonfx/log/*.log
+
+      - if: steps.android_gluon_build.outcome == 'failure'
+        name: Exit if Android Gluon build failed
+        run: exit 1
 
       # Staging 6)
       - if: matrix.gluon-android-arch-token != null
-        name: Copy Android native application to staging
-        run: cp ${{ env.app-gluon-module-dir }}/target/gluonfx/${{ matrix.gluon-android-arch-token }}/gvm/*.apk staging/${{ env.app-name }}-${{ matrix.gluon-android-artifact-suffix }}
+        name: Copy Android APK & AAB to staging
+        run: |
+          cp ${{ env.app-gluon-module-dir }}/target/gluonfx/${{ matrix.gluon-android-arch-token }}/gvm/*.apk staging/${{ env.app-name }}-${{ matrix.gluon-android-apk-suffix }}
+          cp ${{ env.app-gluon-module-dir }}/target/gluonfx/${{ matrix.gluon-android-arch-token }}/gvm/*.aab staging/${{ env.app-name }}-${{ matrix.gluon-android-aab-suffix }}
 
+      # Uploading to Google Play (if json provided)
+      - if: matrix.gluon-ios-arch-token != null && env.GLUON_ANDROID_SERVICE_ACCOUNT_JSON != ''
+        name: Upload to Google Play
+        uses: r0adkll/upload-google-play@v1.0.19
+        with:
+          serviceAccountJsonPlainText: ${{ env.GLUON_ANDROID_SERVICE_ACCOUNT_JSON }}
+          packageName: ${{ matrix.android-package-name }}
+          releaseFiles: ${{ env.app-gluon-module-dir }}/target/gluonfx/${{ matrix.gluon-android-arch-token }}/gvm/*.aab
+          track: ${{ matrix.android-track }}
 
       ##################################################################################################################
       #                        Building and staging the native iOS app using Gluon/GraalVM                             #
@@ -323,23 +386,23 @@ jobs:
       ##################################################################################################################
 
       # Importing the Apple codesign certificates
-      - if: env.GLUON_IOS_CERTIFICATES_FILE_BASE64 != ''
+      - if: env.GLUON_IOS_CERTIFICATES_BASE64 != ''
         uses: Apple-Actions/import-codesign-certs@v1
         with:
-          p12-file-base64: ${{ secrets.GLUON_IOS_CERTIFICATES_FILE_BASE64 }}
-          p12-password: ${{ secrets.GLUON_IOS_CERTIFICATES_PASSWORD }}
+          p12-file-base64: ${{ env.GLUON_IOS_CERTIFICATES_BASE64 }}
+          p12-password: ${{ env.GLUON_IOS_CERTIFICATES_PASSWORD }}
 
       # Importing the Apple codesign certificates
       - if: env.GLUON_IOS_APPSTORE_KEY_ID != ''
         uses: Apple-Actions/download-provisioning-profiles@v1
         with:
           ios-bundle-id: ${{ matrix.app.ios-bundle-id }}
-          issuer-id: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
-          api-key-id: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
-          api-private-key: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
+          issuer-id: ${{ env.GLUON_IOS_APPSTORE_ISSUER_ID }}
+          api-key-id: ${{ env.GLUON_IOS_APPSTORE_KEY_ID }}
+          api-private-key: ${{ env.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
 
       # Invoking the Gluon Client Maven plugin to build the native iOS app (chaining build & package goals)
-      - if: matrix.gluon-ios-arch-token != null && env.GLUON_IOS_CERTIFICATES_FILE_BASE64 != ''
+      - if: matrix.gluon-ios-arch-token != null && env.GLUON_IOS_CERTIFICATES_BASE64 != ''
         name: Gluon Build for iOS
         run: mvn -B -P 'gluon-ios' clean gluonfx:build gluonfx:package # May take a while
         env:
@@ -347,7 +410,7 @@ jobs:
         working-directory: ${{ env.app-gluon-module-dir }}
 
       # Staging 10)
-      - if: matrix.gluon-ios-arch-token != null && env.GLUON_IOS_CERTIFICATES_FILE_BASE64 != ''
+      - if: matrix.gluon-ios-arch-token != null && env.GLUON_IOS_CERTIFICATES_BASE64 != ''
         name: Copy iOS native application to staging
         run: cp ${{ env.app-gluon-module-dir }}/target/gluonfx/${{ matrix.gluon-ios-arch-token }}/gvm/*.ipa staging/${{ env.app-name }}-${{ matrix.gluon-ios-artifact-suffix }}
 
@@ -362,9 +425,9 @@ jobs:
         uses: Apple-Actions/upload-testflight-build@master
         with:
           app-path: staging/${{ env.app-name }}-${{ matrix.gluon-ios-artifact-suffix }}
-          issuer-id: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
-          api-key-id: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
-          api-private-key: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
+          issuer-id: ${{ env.GLUON_IOS_APPSTORE_ISSUER_ID }}
+          api-key-id: ${{ env.GLUON_IOS_APPSTORE_KEY_ID }}
+          api-private-key: ${{ env.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
 
 
       ##################################################################################################################
@@ -392,8 +455,8 @@ jobs:
       ##################################################################################################################
 
       # Uploading all artifacts in the assets of this workflow run
-      - name: Upload artifacts in the assets of this worflow run
-        uses: actions/upload-artifact@v2
+      - name: Upload artifacts in the assets of this workflow run
+        uses: actions/upload-artifact@v3
         with:
           name: build-${{ matrix.os-config }}-assets
           path: staging/*
@@ -437,7 +500,7 @@ jobs:
           tag: SNAPSHOT
           assets: '*'
           fail-if-no-assets: false
-          token: ${{ secrets.API_GITHUB_TOKEN }}
+          token: ${{ env.API_GITHUB_TOKEN }}
 
       # Upload all artifacts into the SNAPSHOT release assets
       - if: env.API_GITHUB_TOKEN != ''
@@ -446,4 +509,4 @@ jobs:
         with:
           release-tag: SNAPSHOT
           files: upload/*
-          repo-token: ${{ secrets.API_GITHUB_TOKEN }}
+          repo-token: ${{ env.API_GITHUB_TOKEN }}
